In [1]:
## Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

print("Original Array:\n", arr)

# Interchange rows and columns (transpose the array)
transposed_arr = arr.T

print("Transposed Array:\n", transposed_arr)


Original Array:
 [[79 17 27]
 [82 22 70]
 [12 18  3]]
Transposed Array:
 [[79 82 12]
 [17 22 18]
 [27 70  3]]


In [2]:
## Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

print("Original 1D Array:\n", array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
## Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:\n", array_4x4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:\n", array_with_border)


Original 4x4 Array:
 [[0.07439838 0.48746204 0.98417549 0.88766478]
 [0.92976261 0.42105449 0.35313558 0.50366707]
 [0.60950533 0.33381723 0.33502731 0.69460659]
 [0.81329092 0.08877457 0.6455371  0.57394004]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.07439838 0.48746204 0.98417549 0.88766478 0.        ]
 [0.         0.92976261 0.42105449 0.35313558 0.50366707 0.        ]
 [0.         0.60950533 0.33381723 0.33502731 0.69460659 0.        ]
 [0.         0.81329092 0.08877457 0.6455371  0.57394004 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
## Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:\n", array_integers)


Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [5]:
##. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
capitalize_array = np.char.capitalize(array_strings)

# Display the results
print("Original Array:\n", array_strings)
print("\nUppercase:\n", uppercase_array)
print("\nLowercase:\n", lowercase_array)
print("\nTitle Case:\n", titlecase_array)
print("\nCapitalized:\n", capitalize_array)


Original Array:
 ['python' 'numpy' 'pandas']

Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
 ['python' 'numpy' 'pandas']

Title Case:
 ['Python' 'Numpy' 'Pandas']

Capitalized:
 ['Python' 'Numpy' 'Pandas']


In [6]:
## Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Create a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', array_words)

# Display the results
print("Original Array:\n", array_words)
print("\nArray with spaces between characters:\n", spaced_array)


Original Array:
 ['hello' 'world' 'numpy' 'python']

Array with spaces between characters:
 ['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [7]:
## Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                    [40, 50, 60]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Display the results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[10 20 30]
 [40 50 60]]

Element-wise Addition:
 [[11 22 33]
 [44 55 66]]

Element-wise Subtraction:
 [[ -9 -18 -27]
 [-36 -45 -54]]

Element-wise Multiplication:
 [[ 10  40  90]
 [160 250 360]]

Element-wise Division:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [8]:
##. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [9]:
## Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check for primality
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Random Integers Array:\n", random_integers)
print("\nPrime Numbers in the Array:\n", prime_numbers)


Random Integers Array:
 [268 890 316 976 861 406  93 276 148 422 239 275 365 338 919 911 883 655
 326 665 574 886  71 345 723 303 598 792 760 591 694 883 219 295  39 940
 761 459 922 141 100 371 623 351 286 725 136 544 113 637 880 407 474  83
 285 696  87 778 742 674 840 520 779 796 240 335 967  17 339 756 669 159
 177 951 830 263 571 221 883 409 498 499 103 917 468 290 313  77 845 861
 915 682 331 563 143 666 651 742 677 804]

Prime Numbers in the Array:
 [239, 919, 911, 883, 71, 883, 761, 113, 83, 967, 17, 263, 571, 883, 409, 499, 103, 313, 331, 563, 677]


In [16]:
##  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For this example, we'll use a fixed range of temperatures between 10 and 35 degrees Celsius
daily_temperatures = np.array([20, 22, 25, 18, 30, 32, 28,
                                25, 26, 24, 30, 31,
                                15, 20, 22, 29, 27,
                                35, 33, 31, 28,
                                24, 22, 21, 19,
                                17, 15, 10, 12,
                                18, 21, 32, ])

print("Daily Temperatures for the Month:\n", daily_temperatures)

# Reshape the array into a 4-week format (assuming 30 days)
# We can create 4 weeks of 7 days, and the last row will have only 2 days.
weekly_temperatures = daily_temperatures.reshape(4, 8)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("\nWeekly Averages:\n", weekly_averages)




Daily Temperatures for the Month:
 [20 22 25 18 30 32 28 25 26 24 30 31 15 20 22 29 27 35 33 31 28 24 22 21
 19 17 15 10 12 18 21 32]

Weekly Averages:
 [25.    24.625 27.625 18.   ]
